### PR TITLE
SES-1066: Update OpenJDK to Java 8 version 222

### PR DESCRIPTION
**Pull request by ryanJsonar**

### CODE REVIEW

**Comment by yhagerjs** [comment]
There is no need for that. in your project, call  
```
add_java_dependency(JAVA_VERSION 1:1.8.0.222)
```
This is only changing the default.

**Comment by luigiJsonar** [comment]
@yhager I think we decided to do this because all the java projects should use the same Java version (we don't want to depend on more than one version). Do you have a suggestion on how we should do this if not here?

**Comment by yhagerjs** [comment]
Yeah... Unfortunately it's not enforceable either way, but if you are more comfortable with this way, then do it the way you like (read: you can merge this).

**Comment by oorijsonar** [comment]
I thought we were at 232 now.

**Pull request merged**
