### PR TITLE
use --first-parent so we ignore merged tags

### PR DESCRIPTION
**Pull request by jsonar-cpapke**

### CODE REVIEW

**Comment by oorijsonar** [comment]
Where is this necessary? Is there an example repo and branch?

**Comment by jsonar-cpapke** [comment]
sonarpy

```
> git checkout master
> git describe
v4.4.1-3-10-gcffcccb
> git describe --first-parent
v4.5.0-devel-4-gcffcccb
> git checkout Release_4.4
> git describe
v4.4.1-3-1-g9610b87
```

**Review by oorijsonar — APPROVED** [review]

**Review by yhager — APPROVED** [review]
I've tested this and I confirm that this is what we want. Thanks!

**Comment by yhager** [comment]
@oorijsonar `git describe` will return the most recent tag, on all branches. We don't want to take tags from merged branches, which is exactly what `--first-parent` does. It basically cements our requirement that merges only go from older to newer release branches - otherwise we will get the wrong tags

**Pull request merged**
