### PR TITLE
Fix building shared bzip2 when using Ninja

### PR DESCRIPTION
**Pull request by michaelJSonar**

### CODE REVIEW

**Review by pablojSonar — APPROVED** [review]

**Comment by jsonar-cpapke** [comment]
If you are trying to fix your `Release_4.4`/`master`(and probably `develop`) you will need to update `master` here, not `sonarw`.

**Comment by pablojSonar** [comment]
The shared version of `bzip2` is only used in `develop` for now Chris

**Comment by jsonar-cpapke** [comment]
Hmm, I had thought I saw this error elsewhere, but I guess I was wrong. I can't find whatever I thought I saw now.

**Comment by jsonar-cpapke** [comment]
sonarw master will still need some changes from the latest cmake master branch to keep working though.

**Review by yhager — CHANGES_REQUESTED** [review]
No, we are not building shared libraries. If you want to do so on sonarw, do so there. Do not push these commits in cmake, I do not approve

**Comment by michaelJSonar** [comment]
@yhager we were already building a shared bzip2 (in the `sonarw` branch only) for a month or so now, I'm just fixing a bug. cc @arthurJsonar I can just do this directly in our repo instead if that's easier for everybody.

**Comment by yhager** [comment]
Whatever's happening in sonarw branch was never approved by me. I was asked to review this so I did. 
I can't tell you what to do on your own project, but if you want to maintain your own build system, as long as it's approved by Ury, it's fine by me. 
This build system is common to all jsonar projects and have served us well. We cannot afford to introduce shared libraries to it at the moment. It caused a lot of trouble in the past and it's been hard work (still not completed btw) to clean it up.

**Comment by arthurJsonar** [comment]
> Whatever's happening in sonarw branch was never approved by me. I was asked to review this so I did.
> I can't tell you what to do on your own project, but if you want to maintain your own build system, as long as it's approved by Ury, it's fine by me.
> This build system is common to all jsonar projects and have served us well. We cannot afford to introduce shared libraries to it at the moment. It caused a lot of trouble in the past and it's been hard work (still not completed btw) to clean it up.

@yhager That's why I have my branch, so I don't need to have silly discussions with somebody that is WAY out of line.

**Pull request merged**
