### PR TITLE
Change RPM name

### PR DESCRIPTION
**Pull request by pearseimperva**
This change would modify the default rpm name so it matches
```
{package_name}-{version}-{release}.{arch}.rpm 
```

### CODE REVIEW

**Comment by yhager** [comment]
Only the vendor is the difference, right? You can make the vendor a parameter, and when it does not exist, skip it.
Does that take care of all the differences in the naming scheme?
Or we can remove the vendor completely. I'm not too concerned with changing the default here. There is no use for the RPM builders other than the archiver at the moment, so as long as your changes are not archiver specific, they can go into the generic RPM related code

**Comment by pearseimperva** [comment]
This is what I get right now `sonar_archiver-0.0.0-43-g45c710e.el7.jsonar.x86_64.rpm`, so the difference is it has the `el7.jsonar` but it's missing the release number from `CPACK_RPM_PACKAGE_RELEASE`. 

If it's okay to change the default then that's definitely the easiest thing to do.

**Comment by yhager** [comment]
Yes, I think it's okay to change the default. @jsonar-cpapke do you have any issues with that?
Where is the release number coming from?

**Comment by jsonar-cpapke** [comment]
I don't think there would be any reason not to add the `el7.jsonar` for everything. Seems to me that would make sense. Except for one point, can you use `el7.sonar`, as I think that is more correct now 😉

**Comment by pearseimperva** [comment]
@yhager I didn't see `CPACK_RPM_PACKAGE_RELEASE` set anywhere so I just set it in archiver's `pkg/CMakeList.txt`. I'll check if they are opposed to us keeping `el7.jsonar` in the name.

**Comment by yhager** [comment]
If we must have a release there, let's just hard-code the release to "1" (in cmake repo, archiver should have nothing to say about it). We have major.minor.patch, and those are more then enough to convey code change. We don't really have a use for a release field.

**Comment by pearseimperva** [comment]
I talked with Chen Yachin, who brought up the issue in the first place and there are two things he wants:
1. The RPM name to match [this convention](http://ftp.rpm.org/max-rpm/ch-rpm-file-format.html), so he would like the vendor tag removed in order to match it.
2. The file name to match the output of `rpm -qp --queryformat "%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm\n" <sonar_archiver_rpm>`.  The difference right now the version in the filename has hyphens (0.0.0-50-g135cdb2), whereas the version property associated with the rpm has underscores. I think CPack automatically converts hyphen to dashes in CPACK_PACKAGE_VERSION.

**Review by yhager — APPROVED** [review]

**Pull request merged**
